---
- name: installing a httpd package
  hosts: all
  become: true
  tasks:

  - name: installing a httpd package
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: installing a apache2 service
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy a file
    copy:
      src: /home/ansibleadmin/index.html
      dest: var/www/html
      mode: 0777
