---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: Install java in RedHat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install a java in Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.75/bin/apache-tomcat-8.5.75.tar.gz
      dest: /opt
  - name: extract tomcat
    unarchive:
      src: /opt/apache-tomcat-8.5.75.tar.gz
      dest: /opt
      remote_src: true

  - name: Execute file permissions
    file:
      path: /opt/apache-tomcat-8.5.75/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.75/bin


