---
# tasks file for setup-apache-role
- name: installing a httpd package
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: start httpd service
- name: installing a apache2 service
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: create a directory
  file:
    path: /home/ansibleadmin/demo
    state: directory

- name: copy a file
  copy:
      src: /home/ansibleadmin/index.html
      dest: var/www/html
      mode: 0777


